version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    depends_on:
      - postgres_db
      - redis

  postgres_db:
    image: postgres:14.6-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"


  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"


  celery:
    image: celery:latest
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - redis
      - django
    links:
      - redis
