# Generated by Django 4.2.7 on 2024-01-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_code_verified_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_verified',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
